version: '3'

services:
    db:
        image: mysql:5.7
        container_name: wordpress_db
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        env_file:
            - db.env
        restart: always

    wordpress:
        image: wordpress:5
        container_name: wordpress_app
        volumes:
            - ./themes:/var/www/html/wp-content/themes
            - ./plugins:/var/www/html/wp-content/plugins
        ports:
            - "127.0.0.1:8000:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_CONFIG_EXTRA: |
                define('AUTOMATIC_UPDATER_DISABLED', true);
        env_file:
            - wp.env
        depends_on:
            - db
        restart: always

volumes:
    db_data:
